---
title: "South Sudan resilience baseline"
subtitle: "Survey frequencies"
author: "Dan Killian"
toc: true
toc-depth: 3
number-sections: true
format: 
  html:
    code-fold: true
editor: visual
---

```{r global_options, include=F, warning=F, message=F, echo=F, error=F}

# standard figure size and generate clean output
knitr::opts_chunk$set(autodep=T, fig.height=4, fig.width=6, warning=FALSE, message=FALSE, cache=TRUE, error=T, echo=T)

library(here)
source("00 South Sudan resilience - prep.R")
```

# Household Income and Consumption

## Overall

```{r}
inc_ov_tmp <- svyrdat %>%
  group_by() %>%
  summarize(crop_production=survey_mean(q_401_a_bin),
            cattle_production = survey_mean(q_401_b_bin),
            goat_production = survey_mean(q_401_c_bin),
            sheep_production = survey_mean(q_401_d_bin),
            fishing = survey_mean(q_401_e_bin),
            Agwage_within = survey_mean(q_401_f_bin),
            Agwage_without = survey_mean(q_401_g_bin),
            nonAgwage_within = survey_mean(q_401_h_bin),
            nonAgwage_without = survey_mean(q_401_i_bin),
            salary = survey_mean(q_401_j_bin),
            bush_products = survey_mean(q_401_k_bin),
            honey = survey_mean(q_401_l_bin),
            petty_trade_other = survey_mean(q_401_m_bin),
            petty_trade_own = survey_mean(q_401_n_bin),
            ownbiz_ag = survey_mean(q_401_o_bin), 
            ownbiz_nonag = survey_mean(q_401_p_bin),
            rent = survey_mean(q_401_q_bin),
            remit = survey_mean(q_401_r_bin),
            gifts = survey_mean(q_401_s_bin),
            safety_net = survey_mean(q_401_t_bin)) 

```

```{r}
ov_cols <- seq_len(40) %% 2

inc_ov_mn <- inc_ov_tmp[, ov_cols==T] %>%
    pivot_longer(cols=1:20,
               names_to="income_source",
               values_to="Percent") %>%
  mutate(inc_lab=inc_labs) %>%
  relocate(inc_lab, .after=income_source)

inc_ov_se <- inc_ov_tmp[,ov_cols==F] %>%
  pivot_longer(cols=1:20,
               names_to="income_source",
               values_to="se")

inc_ov <- inc_ov_mn %>%
  bind_cols(inc_ov_se[,2]) %>%
  mutate(margin=se*1.96,
         lower=Percent-margin,
         upper=Percent+margin)

inc_gt <- inc_ov %>%
  select(-1, -4) %>%
  arrange(desc(Percent)) %>%
  gt() %>%
  fmt_percent(2:5,
              decimals=1) %>%
  cols_label(inc_lab="Income source") %>%
  tab_source_note("Survey instsrument items 401a-t")
  

inc_gt

```

## By county

### Long format, with confidence intervals

```{r}
inc_cnty_tmp <- svyrdat %>%
  group_by(county) %>%
  summarize(crop_production=survey_mean(q_401_a_bin),
            cattle_production = survey_mean(q_401_b_bin),
            goat_production = survey_mean(q_401_c_bin),
            sheep_production = survey_mean(q_401_d_bin),
            fishing = survey_mean(q_401_e_bin),
            Agwage_within = survey_mean(q_401_f_bin),
            Agwage_without = survey_mean(q_401_g_bin),
            nonAgwage_within = survey_mean(q_401_h_bin),
            nonAgwage_without = survey_mean(q_401_i_bin),
            salary = survey_mean(q_401_j_bin),
            bush_products = survey_mean(q_401_k_bin),
            honey = survey_mean(q_401_l_bin),
            petty_trade_other = survey_mean(q_401_m_bin),
            petty_trade_own = survey_mean(q_401_n_bin),
            ownbiz_ag = survey_mean(q_401_o_bin), 
            ownbiz_nonag = survey_mean(q_401_p_bin),
            rent = survey_mean(q_401_q_bin),
            remit = survey_mean(q_401_r_bin),
            gifts = survey_mean(q_401_s_bin),
            safety_net = survey_mean(q_401_t_bin)) 
```

```{r}
cnty_cols <- seq_len(41) %% 2

inc_cnty_mn <- inc_cnty_tmp[, cnty_cols==F] %>%
  mutate(county=county_key$county) %>%
  relocate(county, .before=1) %>%
  pivot_longer(cols=2:21,
               names_to="income_source",
               values_to="Percent") %>%
  mutate(inc_lab = rep(inc_labs, 13))

inc_cnty_se <- inc_cnty_tmp[,cnty_cols==T] %>%
  pivot_longer(cols=2:21,
               names_to="income_source",
               values_to="se")

inc_cnty <- inc_cnty_mn %>%
  bind_cols(inc_cnty_se[,3]) %>%
  mutate(margin=se*1.96,
         lower=Percent-margin,
         upper=Percent+margin) %>%
  relocate(inc_lab, .after=income_source)

inc_cnty_gt <- inc_cnty %>% 
  select(-2, -5) %>%
  gt() %>%
  fmt_percent(3:6, 
              decimals=1) %>%
  cols_label(county="County",
             inc_lab="Income source")

inc_cnty_gt
```

### Wide format to better show income source across county. 

```{r}

inc_cnty_wide <- inc_cnty %>%
  select(1,3,4) %>%
  as.data.frame() %>%
  pivot_wider(names_from=county,
              values_from=Percent)


inc_cnty_wide_gt <- inc_cnty_wide %>%
  gt() %>%
  fmt_percent(2:14,
              decimals=0) %>%
  cols_label(inc_lab="Income source")

inc_cnty_wide_gt
```

# Food insecurity

## Food insecure behavior in previous 12 months

```{r}

q422 <- svy_disag(svyrdat, "", q_422, "worried", "Worried about not enough to eat") %>%
  select(4,5,2,6,7)

#q422

q423 <- svy_disag(svyrdat, "", q_423, "unhealthy", "Unable to eat healthy") %>%
  select(4,5,2,6,7)

#q423

q424 <- svy_disag(svyrdat, "", q_424, "few_foods", "Ate few kinds of foods") %>%
  select(4,5,2,6,7)

#q424

q425 <- svy_disag(svyrdat, "", q_425, "skip", "Skipped a meal") %>%
  select(4,5,2,6,7)

#q425

q426 <- svy_disag(svyrdat, "", q_426, "ate_less", "Ate less than needed") %>%
  select(4,5,2,6,7)

#q426

q427 <- svy_disag(svyrdat, "", q_427, "no_food", "Did not have food") %>%
  select(4,5,2,6,7)

#q427

q428 <- svy_disag(svyrdat, "", q_428, "not_eat", "Did not eat") %>%
  select(4,5,2,6,7)

#q428

q429 <- svy_disag(svyrdat, "", q_429, "wholeday", "Went a day without eating") %>%
  select(4,5,2,6,7)

#q429

fies_items <- do.call(rbind, 
                      list(q422,
                           q423,
                           q424,
                           q425,
                           q426,
                           q427,
                           q428,
                           q429))


#fies_items


```

```{r}
fies_items_gt <- fies_items %>%
  select(-1) %>%
  gt() %>%
  fmt_percent(2:4,
              decimals=1) %>%
  cols_label(label="In previous 12 months..",
             Value="Percent") %>%
  tab_source_note("Survey instrument items 422-429") #%>%
  #tab_source_note("Behavior in past 12 months")

fies_items_gt

#gtsave(fies_items_gt, here("output/tables/food insecurity/fies items.rtf"))
```

## Food insecure behavior in previous four weeks

```{r}

q430 <- svy_disag(svyrdat, "", q_430, "no_food", "No food in house") %>%
  select("In previous four weeks.."=5,Percent=2,6,7) %>%
  gt() %>%
  fmt_percent(2:4,
              decimals=1) 

q430

```

```{r}

# need to use survey package due to presence of not asked 

q431 <- svytable(~q_431,
                     svydat,
                     Ntotal=T) %>%
  as.data.frame() %>%
  mutate(Response=c("Rarely (1-2 times)",
                    "Sometimes (3-10 times)",
                    "Often (More than 10 times)")) %>%
  select(3,Percent=2) %>%
  gt() %>%
  fmt_percent(2,
              decimals=1) %>%
  cols_label(Response=html("How often no food in house<br>in previous four weeks?"))

q431
```

```{r}

q432 <- svy_disag(svyrdat, "", q_432, "slept_hungry", "Went to bed hungry") %>%
  select(5,Percent=2,6,7) %>%
  gt() %>%
  fmt_percent(2:4,
              decimals=1) %>%
  cols_label(label="In the previous four weeks..")

q432

```

```{r}

# need to use survey package due to presence of not asked 

q433 <- svytable(~q_433,
                     svydat,
                     Ntotal=T) %>%
  as.data.frame() %>%
  mutate(Response=c("Rarely (1-2 times)",
                    "Sometimes (3-10 times)",
                    "Often (More than 10 times)")) %>%
  select(3,Percent=2) %>%
  gt() %>%
  fmt_percent(2, 
              decimals=1) %>%
  cols_label(Response=html("How often went to bed<br>hungry in past four weeks?"))

q433
```

```{r}
q434 <- svy_disag(svyrdat, "", q_434, "fast", "Went whole day without eating") %>%
  select(5,Percent=2,6,7) %>%
  gt() %>%
  fmt_percent(2:4,
              decimals=1) %>%
  cols_label(label="In the previous four weeks..")

q434
```

```{r}

# need to use survey package due to presence of not asked 

q435 <- svytable(~q_435,
                     svydat,
                     Ntotal=T) %>%
  as.data.frame() %>%
  mutate(Response=c("Rarely (1-2 times)",
                    "Sometimes (3-10 times)",
                    "Often (More than 10 times)")) %>%
  select(3,Percent=2) %>%
  gt() %>%
  fmt_percent(2, 
              decimals=1) %>%
  cols_label(Response=html("How often went a whole day<br>without eating in past four weeks?"))

q435
```

# Household involvement in the community

## Community group participation

```{r}

grps_sum <- read_csv(here("output/tables/resilience/groups weighted.csv"))

grps_sum_gt <- grps_sum %>%
  gt()

grps_sum_gt
```
